routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// landing page redirect to login
Route::get('/', function () {
    return Redirect::to('login');
})->name('landing');
// auth vanilla from laravel
Auth::routes();

// change language
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

Route::group(['middleware' => 'auth'], function(){
    // diffrence between USER and ADMIN (Home View)
    // for admin
    Route::resource('/home', 'HomeController')->middleware('level'); 
    // for user
    Route::prefix('user')->name('user.')->group(function () {
        Route::resource('/home', 'User\HomeController');
    });
    // profile
    Route::resource('/profile', 'ProfileController');
    Route::get('/profile/{id}/password', 'ProfileController@editPassword');

    // Stock that can be access by User
    // Stock Now
    Route::get('/stocknow/export_pdf', 'StockNowController@exportPdf');
    Route::resource('/stocknow', 'StockNowController');
    // Export Stockout/Transaction
    Route::get('/stockout/export_pdf/{id}', 'StockOutController@exportSinglePdf')->name('stockout.export');
    // Transaction(request stockout)
    Route::get('/transaction/summary', 'TransactionController@summary');
    Route::get('/transaction/checkid', 'TransactionController@checkId')->name('transaction.checkid');
    Route::resource('/transaction', 'TransactionController');
    // cart
    Route::post('/cart/store', 'CartController@store')->name('cart.store');
    // Route::get('/cart/store_demo', 'CartController@storeDemo')->name('cart.store_demo'); // storing dummy goodies for development purpose
    Route::get('/cart/list', 'CartController@list')->name('cart.list');
    Route::get('/cart/clear', 'CartController@clear')->name('cart.clear');
    Route::get('/cart/{id}/stock', 'CartController@getStock')->name('cart.stock');
    Route::resource('/cart', 'CartController');
    // Stock Out
    Route::resource('/stockout/item', 'StockOutItemController',['as' => 'stockout']); // for Stockout items(edit/detail)

    Route::group(['middleware' => 'level'], function(){
        // for MASTER
        // category
        Route::post('/category/store_stockin', 'CategoryController@storeStockin')->name('category.store_stockin'); // store category from Stock In Page
        Route::resource('/category', 'CategoryController');
        // unit
        Route::post('/unit/store_stockin', 'UnitController@storeStockin')->name('unit.store_stockin'); // store unit from Stock In Page
        Route::resource('/unit', 'UnitController');
        // goody
        Route::post('/goody/store_stockin', 'GoodyController@storeStockin')->name('goody.store_stockin'); // store goody from Stock In Page
        Route::resource('/goody', 'GoodyController');
        // user
        Route::resource('/user', 'UserController');

        // ALL TRANSACTION(STOCK)
        // Stock Out
        Route::resource('/stockout', 'StockOutController');
        // Stock In
        Route::get('/stockin/summary', 'StockInController@summary');
        Route::get('/stockin/checkid', 'StockInController@checkId')->name('stockin.checkid');
        Route::get('/stockin/export_pdf/{id}', 'StockInController@exportSinglePdf');
        Route::resource('/stockin', 'StockInController');
        // Stock Opname
        Route::get('/stockopname/summary', 'StockOpnameController@summary');
        Route::get('/stockopname/checkid', 'StockOpnameController@checkId')->name('stockopname.checkid');
        Route::get('/stockopname/export_pdf/{id}', 'StockOpnameController@exportSinglePdf');
        Route::resource('/stockopname', 'StockOpnameController');
        // Setting
        Route::prefix('setting')->group(function () {
            Route::get('/', 'SettingController@index')->name('setting');
            Route::post('/building', 'SettingController@storeBuilding')->name('setting.building');
        });
    });
});

app/Http/Controllers/Api/TransactionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\StockOut;

use Carbon\Carbon;
use DataTables;

class TransactionController extends Controller
{
    public function getUser()
    {
        $users = User::select();
        return Datatables::of($users)
            ->addColumn('details_url', function($user) {
                return route('api.transaction_single', $user->id);
            })->make(true);
    }

    public function getSingleUser($id)
    {
        $transactions = User::findOrFail($id)->transactions->sortByDesc('created_at');

        foreach($transactions as $transaction){
            $transaction->description = \Illuminate\Support\Str::limit($transaction->description, 40, '...');
            $transaction->status = ucfirst($transaction->status);
            $transaction->confirmation = ucfirst($transaction->confirmation);
        }

        return Datatables::of($transactions)
            ->addColumn('action', function($data){
                return $this->getActionColumn($data);
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    protected function getActionColumn($data)
    {
        $printUrl = action('StockOutController@exportSinglePdf', $data->id);
        $showUrl = action('TransactionController@show', $data->id);
        $btn = ' <a href="'.$printUrl.'" class="btn btn-success btn-circle btn-sm mb-1"><i class="fas fa-print"></i></a> ';
        $btn = $btn.' <a href="'.$showUrl.'" class="btn btn-primary btn-circle btn-sm mb-1"><i class="fas fa-eye"></i></a> ';
        return $btn;
    }

    public function getPermonth($date)
    {
        $month = Carbon::parse($date)->format('Y-m');
        $stocks = StockOut::where('date', 'like', '%' . $month . '%')->with('create_by')->get()->sortByDesc('created_at');
        foreach ($stocks as $stock) {
            $stock->create_by->name = \Illuminate\Support\Str::limit($stock->create_by->name , 20, '...');
            $stock->status = ucfirst($stock->status);
            $stock->confirmation = ucfirst($stock->confirmation);
            isset($stock->description)?$stock->description = \Illuminate\Support\Str::limit($stock->description, 30, '...'):$stock->description = "-";
        }
        return Datatables::of($stocks)
            ->addColumn('action', function($data){
                return $this->getActionColumn($data);
            })
            ->rawColumns(['action'])
            ->addIndexColumn()->make(true);
    }

    public function getPerproject($project)
    {
        $stocks = StockOut::where('description', 'like', '%' . $project . '%')->get()->sortByDesc('created_at');
        foreach ($stocks as $stock) {
            $stock->create_by->name = \Illuminate\Support\Str::limit($stock->create_by->name , 20, '...');
            $stock->status = ucfirst($stock->status);
            $stock->confirmation = ucfirst($stock->confirmation);
            isset($stock->description)?$stock->description = \Illuminate\Support\Str::limit($stock->description, 30, '...'):$stock->description = "-";
        }
        return Datatables::of($stocks)
            ->addColumn('action', function($data){
                return $this->getActionColumn($data);
            })
            ->rawColumns(['action'])
            ->addIndexColumn()->make(true);
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Goody;
use App\User;
use App\StockOut;
use App\StockOutItem;

use Carbon\Carbon;
use Cart;
use DataTables;

use App\Mail\StockoutCreated;
use Illuminate\Support\Facades\Mail;

class TransactionController extends Controller
{
    public function index()
    {
        return view('transaction.index');
    }
    
    public function create()
    {
        return view('transaction.create');
    }

    public function summary()
    {
        if(Cart::isEmpty()){
            return redirect()->route('transaction.create')
                ->with('error','Cart must be fill.');
        }
        return view('transaction.summary');
    }

    public function checkId()
    {
        $stock = StockOut::latest()->first();
        return response()->json(compact('stock'));
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'created_by'           => 'required',
            'id_transaction'       => 'required|unique:stock_out',
            // 'description'          => 'required',
        ]);

        $date = Carbon::parse($request->date)->format('Y-m-d');//for date column

        $stock = new StockOut;
        $stock->id_transaction = $request->id_transaction;
        $stock->date = $date;
        $stock->description = $request->description;
        $stock->created_by = $request->created_by;
        $stock->updated_by = $request->created_by;
        $stock->status = $request->status;
        $stock->confirmation = "unconfirmed";
        $stock->save();

        $stock = StockOut::where('id_transaction', '=', $request->id_transaction)->firstOrFail();//for get id in stock_out
        $cartCollection = Cart::getContent();
        foreach ($cartCollection as $collection){
            $item = new StockOutItem;
            $item->stock_id = $stock->id;
            $item->goody_id = $collection->id;
            $item->qty = $collection->quantity;
            $item->qty_confirm = $collection->quantity;
            $item->description = $collection->attributes->description;
            $item->save();
        }
        Cart::clear();

        // emailing all admin
        $users = User::where('level', '=', 'admin')->get();
        try {
            foreach($users as $user){
                Mail::to($user->email)->send(new StockoutCreated($stock));
            }
        } catch (\Exception $e) {
            return redirect()->route('transaction.index')
                ->with('error','Error when sending email.');
        }

        return redirect()->route('transaction.index')
                ->with('success','Stock Out created Successfully.');
    }

    public function show($id)
    {
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        foreach($stock->items as $item){
            $item->returned = 0;
            foreach($item->stockitem as $item_return){
                $item->returned += $item_return->qty;
            }
            if ($item->returned == $item->qty_confirm) {
                $item->returned = "All";
            }
        }
        return view('transaction.show')->with(compact('stock'));
    }

    // EDIT and UPDATE only in HomeController
    // DESTROY in HomeController and StockOutController

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        // 
    }

    public function destroy($id)
    {
        // 
    }
}

resources/views/transaction/show.blade.php
@extends('layouts.layout')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col-lg-10">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">@lang('transaction.title_detail')</h5>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="id_transaction">@lang('table.id')</label>
                    <input type="text" class="form-control" name="id_transaction" id="id_transaction" readonly disabled value="{{$stock->id_transaction}}">
                </div>
                <div class="form-group">
                    <label for="date">@lang('table.date')</label>
                    <input type="text" class="form-control" name="date" id="date" readonly disabled value="{{$stock->date}}">
                </div>
                <div class="form-group">
                    <label for="user_name">@lang('table.created_by')</label>
                    <input type="text" class="form-control" name="user_name" id="user_name" readonly disabled value="{{$stock->create_by->name}}">
                </div>
                <div class="form-group">
                    <label for="name">@lang('list.goodies')</label>
                    <div class="table-responsive">
                        <table class="table table-bordered display responsive nowrap" id="table" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>@lang('table.name')</th>
                                    <th>@lang('table.code')</th>
                                    <th>@lang('table.qty')</th>
                                    <th>@lang('table.description')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($stock->items as $item)
                                    <tr>
                                        <td width="4%">{{$loop->iteration}}</td>
                                        <td>{{$item->goody->name}}</td>
                                        <td>{{$item->goody->code}}</td>
                                        <td>{{$item->qty_confirm}} {{$item->goody->unit->name}}</td>
                                        <td>{{$item->description}}
                                            @if($item->description),@endif
                                            @if ($stock->status == 'borrow' && ($stock->confirmation == 'done' || $stock->confirmation == 'returned'))
                                                @if (count($item->stockitem))
                                                    <strong> Returned {{$item->returned}}</strong>
                                                @else
                                                    <strong>Not Returned</strong>
                                                @endif
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    {{-- <tr>
                                        <td colspan="5" style="text-align: center">@lang('table.empty')</td>
                                    </tr> --}}
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name">@lang('table.description')</label>
                    <div class="input-group">
                        <textarea readonly class="form-control" id="description" name="description" cols="30" rows="4">{{$stock->description}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="status">@lang('table.status')</label>
                    <input type="text" class="form-control" id="status" readonly disabled value="{{ucfirst($stock->status)}}">
                </div>
                <div class="form-group">
                    <label for="confirmation">@lang('table.confirmation')</label>
                    <input type="text" class="form-control" id="confirmation" readonly disabled value="{{ucfirst($stock->confirmation)}}">
                </div>
                <div class="d-flex justify-content-end text-align-center flex-column flex-md-row">
                    {{-- <a type="button" href="javascript:;" onclick = "history.back()" class="btn btn-outline-secondary mb-2 mb-lg-0 mb-md-0 mr-0 mr-md-2 mr-lg-2">@lang('general.back')</a> --}}
                    <a type="button" href="{{action('TransactionController@index')}}" class="btn btn-outline-secondary mb-2 mb-lg-0 mb-md-0 mr-0 mr-md-2 mr-lg-2">@lang('general.back')</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
@endsection

@section('script')
<script>
    $(document).ready(function() {
        $('#table').DataTable({
            responsive: true,
            paging:   false,
            ordering: false,
            info:     false,
            searching: false,
        });
    })
</script>
@endsection

resources/views/transaction/summary.blade.php
@extends('layouts.layout')

@section('style')
<link href="{{ asset('css/select2.min.css')}}" rel="stylesheet" />
<link href="{{ asset('css/select2-boostrap.css')}}" rel="stylesheet" />

<style>
    .select2-selection__arrow b{
        display:none !important;
    }
</style>
@endsection

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col-lg-10">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">@lang('transaction.title_summary')</h5>
            </div>
            <div class="card-body">
                @if (count($errors) > 0)
                    <p class="card-description"> 
                        <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        </div>
                    </p>
                @endif
                <form action="{{action('TransactionController@store')}}" method="POST" id="transaction-form">
                    @csrf
                    <div class="form-group">
                        <label for="id_transaction">@lang('table.id')</label>
                        <input type="text" class="form-control" name="id_transaction" id="id_transaction" readonly placeholder="ID Transaksi">
                    </div>
                    <div class="form-group">
                        <label for="date">@lang('table.date')</label>
                        <input type="date" class="form-control" name="date" id="date" value="" placeholder="Tanggal Sekarang">
                    </div>
                    <div class="form-group">
                        <label for="created_by">@lang('table.created_by')</label>
                        <input type="hidden" name="created_by" id="created_by" value="{{isset(Auth::user()->id)? Auth::user()->id :""}}">
                        <input type="text" class="form-control" name="user_name" id="user_name" readonly disabled value="{{isset(Auth::user()->name)? Auth::user()->name :""}}" placeholder="Nama User">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('list.goodies')</label>
                        <div class="table-responsive">
                            <table class="table table-bordered display responsive nowrap" id="table" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('table.name')</th>
                                        <th>@lang('table.code')</th>
                                        <th>@lang('table.qty')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="5" style="text-align: center">@lang('table.empty')</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('table.description')</label>
                        <div class="input-group">
                            {{-- <textarea type="text" class="form-control" id="description" name="description" cols="30" rows="4" placeholder="Write description..." autofocus></textarea> --}}
                            <select class="form-control" id="description" name="description"></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('table.status')</label>
                        <div class="input-group">
                            <select id="status" name="status" class="form-control">
                                <option value="request">Request</option>
                                <option value="borrow">Borrow</option>
                                <option value="facility">Facility</option>
                            </select>
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col">
                            <div class="d-flex justify-content-end text-align-center flex-column flex-md-row">
                                <a href="{{ route('transaction.create') }}" class="btn btn-outline-secondary mb-2 mb-lg-0 mb-md-0 mr-0 mr-md-2 mr-lg-2">@lang('general.back')</a>
                                {{-- <button type="submit" class="btn btn-primary"><strong>@lang('transaction.button_create')</strong></button> --}}
                                <button type="button" class="btn btn-primary" id="btn-submit"><strong>@lang('transaction.button_create')</strong></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
@endsection

@section('script')
<script src="{{asset('js/select2.min.js')}}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $.ajax({
            url: "{{ route('api.project.list')}}",
            type: 'GET',
            contentType: 'application/json; charset=utf-8'
        }).then(function (response) {
            $("#description").select2({
                allowClear: true,
                placeholder: {
                    id: "-1",
                    text:"Select a Project",
                    selected:'selected'
                },
                minimumInputLength: 3,
                data: response,
                width: '100%',
                theme: "bootstrap",
                tags: true,
            });
            $('#description').select2('val', '-1');
        });
    });
</script>
<script>
    $(document).ready(function() {
        document.getElementById('date').valueAsDate = new Date();
        let urlCart = "{{ route('cart.index') }}";
        tableCart = $('#table').DataTable({
            ajax: urlCart,
            responsive: true,
            paging:   false,
            ordering: false,
            info:     false,
            searching: false,
            processing:true,
            language: {
                processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span> '
            },
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex' },
                { data: 'name', name: 'name', },
                { data: 'code', name: 'code', },
                { data: 'qty', name: 'qty', },
            ],
        });

        var checkId = function(){
            $.ajax({
                url: "{{ route('transaction.checkid') }}",
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    var idInput = document.getElementById("id_transaction");
                    if(data.stock){
                        var idDb = data.stock.id_transaction;
                        if (idDb.match(/SK.*/)){
                            let addId = parseInt(idDb.split('K')[1])+1;
                            idInput.value = 'SK'+addId;
                        }
                    }else{
                        idInput.value = 'SK1';
                    }
                },
                error: function(data){
                    console.log(data);
                }
            });
        }
        checkId();

        $(document).on('click','#btn-submit',function(){
            $('#btn-submit').html("@lang('general.sending')");
            $('#btn-submit').attr('disabled', true);
            checkId();
            setTimeout(function(){
                $("#transaction-form").submit();
            }, 1000);
        });
    })
</script>
@endsection