routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// landing page redirect to login
Route::get('/', function () {
    return Redirect::to('login');
})->name('landing');
// auth vanilla from laravel
Auth::routes();

// change language
Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'LanguageController@switchLang']);

Route::group(['middleware' => 'auth'], function(){
    // diffrence between USER and ADMIN (Home View)
    // for admin
    Route::resource('/home', 'HomeController')->middleware('level'); 
    // for user
    Route::prefix('user')->name('user.')->group(function () {
        Route::resource('/home', 'User\HomeController');
    });
    // profile
    Route::resource('/profile', 'ProfileController');
    Route::get('/profile/{id}/password', 'ProfileController@editPassword');

    // Stock that can be access by User
    // Stock Now
    Route::get('/stocknow/export_pdf', 'StockNowController@exportPdf');
    Route::resource('/stocknow', 'StockNowController');
    // Export Stockout/Transaction
    Route::get('/stockout/export_pdf/{id}', 'StockOutController@exportSinglePdf')->name('stockout.export');
    // Transaction(request stockout)
    Route::get('/transaction/summary', 'TransactionController@summary');
    Route::get('/transaction/checkid', 'TransactionController@checkId')->name('transaction.checkid');
    Route::resource('/transaction', 'TransactionController');
    // cart
    Route::post('/cart/store', 'CartController@store')->name('cart.store');
    // Route::get('/cart/store_demo', 'CartController@storeDemo')->name('cart.store_demo'); // storing dummy goodies for development purpose
    Route::get('/cart/list', 'CartController@list')->name('cart.list');
    Route::get('/cart/clear', 'CartController@clear')->name('cart.clear');
    Route::get('/cart/{id}/stock', 'CartController@getStock')->name('cart.stock');
    Route::resource('/cart', 'CartController');
    // Stock Out
    Route::resource('/stockout/item', 'StockOutItemController',['as' => 'stockout']); // for Stockout items(edit/detail)

    Route::group(['middleware' => 'level'], function(){
        // for MASTER
        // category
        Route::post('/category/store_stockin', 'CategoryController@storeStockin')->name('category.store_stockin'); // store category from Stock In Page
        Route::resource('/category', 'CategoryController');
        // unit
        Route::post('/unit/store_stockin', 'UnitController@storeStockin')->name('unit.store_stockin'); // store unit from Stock In Page
        Route::resource('/unit', 'UnitController');
        // goody
        Route::post('/goody/store_stockin', 'GoodyController@storeStockin')->name('goody.store_stockin'); // store goody from Stock In Page
        Route::resource('/goody', 'GoodyController');
        // user
        Route::resource('/user', 'UserController');

        // ALL TRANSACTION(STOCK)
        // Stock Out
        Route::resource('/stockout', 'StockOutController');
        // Stock In
        Route::get('/stockin/summary', 'StockInController@summary');
        Route::get('/stockin/checkid', 'StockInController@checkId')->name('stockin.checkid');
        Route::get('/stockin/export_pdf/{id}', 'StockInController@exportSinglePdf');
        Route::resource('/stockin', 'StockInController');
        // Stock Opname
        Route::get('/stockopname/summary', 'StockOpnameController@summary');
        Route::get('/stockopname/checkid', 'StockOpnameController@checkId')->name('stockopname.checkid');
        Route::get('/stockopname/export_pdf/{id}', 'StockOpnameController@exportSinglePdf');
        Route::resource('/stockopname', 'StockOpnameController');
        // Setting
        Route::prefix('setting')->group(function () {
            Route::get('/', 'SettingController@index')->name('setting');
            Route::post('/building', 'SettingController@storeBuilding')->name('setting.building');
        });
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'level', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function transactions()
    {
        return $this->hasMany('App\StockOut', 'created_by', 'id');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\StockOut;
use App\StockOutItem;
use App\Goody;

use App\Mail\StockoutConfirmation;
use Illuminate\Support\Facades\Mail;

class HomeController extends Controller
{
    public function index()
    {
        $stocks = StockOut::where('confirmation', '=', 'unconfirmed')->orWhere('confirmation', '=', 'progress')->get()->sortByDesc('created_at');
        return view('home.index')->with(compact('stocks'));
    }

    public function show($id){
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        return view('home.show')->with(compact('stock'));
    }

    public function edit($id){
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        return view('home.edit')->with(compact('stock'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'updated_by'    => 'required',
            'confirmation'  => 'required',
        ]);
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        $stock->updated_by = $request->updated_by;
        $stock->confirmation = $request->confirmation;
        // update qty in goodies
        if($request->confirmation == 'done'){
            $items = StockOutItem::where('stock_id', '=', $id)->get();
            // checking amount
            $errors = [];
            foreach($items as $item){
                $goody = Goody::where('id', '=', $item->goody_id)->firstOrFail();
                if($goody->qty<$item->qty_confirm){
                    $errors[] = $goody->name." is out of stock, ".$goody->qty. " left in warehouse";
                }
            }
            // checking errors
            if (count($errors)>0){
                // if qty exceed stock, return back and notif error
                return redirect()->route('home.edit', $stock->id)
                    ->with('errors', $errors);
            } else {
                // stock reduced by qty
                foreach($items as $item){
                    $goody = Goody::where('id', '=', $item->goody_id)->firstOrFail();
                    $goody->qty -= $item->qty_confirm;
                    $goody->save();
                }
            }
        }
        $stock->save();
        try {
            Mail::to($stock->create_by->email)->send(new StockoutConfirmation($stock));
        } catch (\Exception $e) {
            return redirect()->route('home.index')
                ->with('error','Error when sending email.');
        }

        return redirect()->route('home.index')
            ->with('success','Stock Out updated successfully.');
    }

    public function destroy($id)
    {
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        $stock->delete();
        return redirect()->route('home.index')
            ->with('success','Stock Out deleted successfully.');
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\StockOut;
use App\User;

use App\Mail\StockoutUpdated;
use Illuminate\Support\Facades\Mail;

class HomeController extends Controller
{
    public function index()
    {
        $stocks = StockOut::where('created_by', '=', auth()->user()->id)->get()->sortByDesc('created_at');
        return view('home.user.index')->with(compact('stocks'));
    }

    public function show($id){
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        return view('home.user.show')->with(compact('stock'));
    }

    public function edit($id){
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        return view('home.user.edit')->with(compact('stock'));
    }

    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'updated_by'    => 'required',
            'confirmation'  => 'required',
        ]);
        $stock = StockOut::where('id', '=', $id)->firstOrFail();
        $stock->updated_by = $request->updated_by;
        $stock->confirmation = $request->confirmation;
        $stock->save();
        $users = User::where('level', '=', 'admin')->get();
        try {
            foreach($users as $user){
                Mail::to($user->email)->send(new StockoutUpdated($stock));
            }
        } catch (\Exception $e) {
            return redirect()->route('user.home.index')
                ->with('error','Error when sending email.');
        }

        return redirect()->route('user.home.index')
            ->with('success','Stock Out updated successfully.');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

use File;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all()->sortBy('name');
        return view('user.index')->with(compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name'      => ['required', 'string', 'max:255'],
            'username'  => ['required', 'string', 'max:255', 'unique:users', 'alpha_dash'],
            'email'     => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password'  => ['required', 'string', 'min:8', 'confirmed'],
            'level'     => ['required', Rule::in(['admin', 'user'])],
            'photo'     => 'required|image|max:2048',
        ]);

        $photo = $request->file('photo');
        $new_name = rand() . '.' . $photo->getClientOriginalExtension();
        $photo->move(public_path('images/users'), $new_name);

        $user = new User;
        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->level = $request->level;
        $user->photo = $new_name;
        $user->save();
        return redirect()->action('UserController@index')
            ->with('success','User created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('user.edit')->with(compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validate = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'level' => ['required', Rule::in(['admin', 'user'])],
        ]);

        if($request->username != $user->username){
            $validate = $request->validate([
                'username' => ['required', 'string', 'max:255', 'unique:users', 'alpha_dash'],
            ]);
        }
        if($request->email != $user->email){
            $validate = $request->validate([
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            ]);
        }
        $validate = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'username' => ['required', 'string', 'max:255', 'alpha_dash'],
            'email' => ['required', 'string', 'email', 'max:255'],
        ]);

        $photo_name = $request->hidden_photo;
        $photo = $request->file('photo');
        if($photo != ''){
            $request->validate([
                'photo'     => 'required|image|max:2048',
            ]);
            $photo_path = "images/users/".$photo_name;  // Value is not URL but directory file path
            if($photo_name != "default.png"){
                if(File::exists($photo_path)) {
                    File::delete($photo_path);
                }
            }
            $photo_name = rand() . '.' . $photo->getClientOriginalExtension();
            $photo->move(public_path('images/users'), $photo_name);
        }

        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->level = $request->level;
        $user->photo = $photo_name;
        $user->save();
        return redirect()->action('UserController@index')
            ->with('success','User updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $photo_path = "images/users/".$user->photo;  // Value is not URL but directory file path
        if($user->photo != "default.png"){
            if(File::exists($photo_path)) {
                File::delete($photo_path);
            }
        }
        $user->delete();
        return redirect()->action('UserController@index')
            ->with('success','User deleted successfully.');
    }
}

resources/views/home/user/edit.blade.php
@extends('layouts.layout')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col-lg-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h5 class="m-0 font-weight-bold text-primary">@lang('home.title_edit')</h5>
            </div>
            <div class="card-body">
                @if (count($errors) > 0)
                    <p class="card-description"> 
                        <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        </div>
                    </p>
                @endif
                <form action="{{action('User\HomeController@update', $stock->id)}}" method="POST">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label for="id_transaction">@lang('table.id')</label>
                        <input type="text" class="form-control" name="id_transaction" id="id_transaction" readonly disabled value="{{$stock->id_transaction}}">
                    </div>
                    <div class="form-group">
                        <label for="date">@lang('table.date')</label>
                        <input type="text" class="form-control" name="date" id="date" readonly disabled value="{{$stock->date}}">
                    </div>
                    <div class="form-group">
                        <label for="created_by">@lang('table.created_by')</label>
                        <input type="text" class="form-control" name="user_created" id="user_created" readonly disabled value="{{$stock->create_by->name}}">
                    </div>
                    <div class="form-group">
                        <label for="updated_by">@lang('table.updated_by')</label>
                        <input type="hidden" name="updated_by" id="updated_by" value="{{isset(Auth::user()->id)? Auth::user()->id :""}}">
                        <input type="text" class="form-control" name="user_updated" id="user_updated" readonly disabled value="{{isset(Auth::user()->name)? Auth::user()->name :""}}">
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('list.goodies')</label>
                        <div class="table-responsive">
                            <table class="table table-bordered display responsive nowrap" id="table" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('table.name')</th>
                                        <th>@lang('table.code')</th>
                                        <th>@lang('table.stock')</th>
                                        <th>@lang('table.qty')</th>
                                        <th>@lang('table.description')</th>
                                        <th>@lang('table.action')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name">@lang('table.description')</label>
                        <div class="input-group">
                            <textarea readonly class="form-control" id="description_form" name="description_form" cols="30" rows="4">{{$stock->description}}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="status">@lang('table.status')</label>
                        <input type="text" class="form-control" id="status" readonly disabled value="{{ucfirst($stock->status)}}">
                    </div>
                    <div class="form-group">
                        <label for="confirmation">@lang('table.confirmation')</label>
                        <select name="confirmation" id="confirmation" class="form-control">
                            <option value="unconfirmed" {{ $stock->confirmation == "unconfirmed" ? 'selected' : '' }}>Unconfirmed</option>
                            <option value="cancel" {{ $stock->confirmation == "cancel" ? 'selected' : '' }}>Cancel</option>
                        </select>
                    </div>
                    <div class="d-flex justify-content-end text-align-center flex-column flex-md-row">
                        <a type="button" href="{{action('HomeController@index')}}" class="btn btn-outline-secondary mb-2 mb-lg-0 mb-md-0 mr-0 mr-md-2 mr-lg-2">@lang('general.back')</a>
                        <button type="submit" class="btn btn-primary"><strong>@lang('general.update')</strong></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

<!-- Modal -->
<div id="editModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <form action="" id="itemForm" name="itemForm">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">@lang('modal.title_item')</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <input type="hidden" class="form-control" id="id" name="id" disabled>
                <div class="form-group">
                    <label for="name">@lang('table.name')</label>
                    <div class="input-group">
                      <input type="text" class="form-control" id="name" name="name" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="code">@lang('table.code')</label>
                    <div class="input-group">
                      <input type="text" class="form-control" id="code" name="code" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="qty">@lang('table.qty_request')</label>
                    <div class="input-group">
                      <input type="number" class="form-control" id="qty" name="qty" min="0" value="1" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="qty_confirm">@lang('table.qty_confirm')</label>
                    <div class="input-group">
                      <input type="number" class="form-control" id="qty_confirm" name="qty_confirm" min="1" value="1">
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">@lang('table.description')</label>
                  <div class="input-group">
                    <textarea class="form-control" id="description" name="description" cols="30" rows="4"></textarea>
                  </div>
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">@lang('general.cancel')</button>
              <button type="submit" class="btn btn-primary" id="editBtn"><strong>@lang('general.add')</strong></button>
            </div>
        </form>
      </div>
    </div>
  </div>
@endsection

@section('script')
<script>
    $(document).ready(function() {
        var urlItem = "{{ route('stockout.item.show', $stock->id) }}";
        table = $('#table').DataTable({
            ajax: urlItem,
            responsive: true,
            paging:   false,
            ordering: false,
            info:     false,
            searching: false,
            columns: [
                { data: 'DT_RowIndex', name: 'DT_RowIndex' },
                { data: 'name', name: 'name', },
                { data: 'code', name: 'code', },
                // { data: 'qty_confirm', name: 'qty', },
                { data: "stock", name: 'stock', 
                    render: function ( data, type, row ) {
                        return row.stock + ' ' + row.unit;
                    }
                },
                { data: "qty_confirm", name: 'qty', 
                    render: function ( data, type, row ) {
                        return row.qty_confirm + ' ' + row.unit;
                    }
                },
                { data: 'description', name: 'description', },
                { data: 'action', name: 'action', },
            ],
        });

        $(function () {
            $.ajaxSetup({
                headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            
            $('body').on('click', '#editItem', function () {
                var item_id = $(this).data('id');
                $('#editBtn').html("@lang('general.wait')");
                var url = '{{ route("stockout.item.edit", ":id") }}';
                url = url.replace(':id', item_id);
                $.get(url, function (data) {
                    $('#editModal').modal('show');
                    $('#id').val(data.id);
                    $('#name').val(data.name);
                    $('#code').val(data.code);
                    $('#description').val(data.description);
                    $('#editBtn').html("@lang('general.update')");
                    document.getElementById("qty").value = data.qty;
                    document.getElementById("qty_confirm").value = data.qty_confirm;
                    document.getElementById("qty_confirm").min = 1;
                    document.getElementById("qty_confirm").max = data.qty;
                })
            });

            // check status single/multiple
            let validd = function(qty, request){
                if (qty > parseInt(request)) {
                    alert("@lang('modal.over_cart_multiple')");
                    document.getElementById("qty_confirm").value = request;
                    $('#editBtn').html("@lang('general.update')");
                    return false;
                }
                console.log(qty+'-'+request);
                return true;
            }

            $('#editBtn').click(function (e) {
                e.preventDefault();
                $(this).html("@lang('general.sending')");
                id = $('#id').val();
                request = $('#qty').val();
                qty = $('#qty_confirm').val();
                description = $('#description').val();

                if(!validd(qty, request)) return false;

                var url = '{{ route("stockout.item.update", ":id") }}';
                url = url.replace(':id', id);
                let type = "PUT";
                
                $.ajax({
                    data:{
                        "_token": "{{ csrf_token() }}",
                        "_method": type,
                        by: "user",
                        id:id,
                        qty:qty,
                        description:description,
                    },
                    url: url,
                    type: type,
                    dataType: 'json',
                    success: function (data) {
                        $('#itemForm').trigger("reset");
                        $('#editModal').modal('hide');
                        $('#editBtn').html("@lang('general.update')");
                        console.log(data);
                        table.ajax.url(urlItem).load();
                    },
                    error: function (data) {
                        console.log('Error:', data);
                        $('#editBtn').html("@lang('general.update')");
                    }
                });
            });
        });
    })
</script>
@endsection